### ISSUE TITLE
Sheet floating for embedded WebView with small amount of content

### ISSUE THREAD

**Issue by svenwiegand** [Flipboard/bottomsheet#91]
I'm using the `BottomSheetLayout` to display a `WebView`. Everything works fine if the `WebView`'s content fills the height of the screen. But if the content is very small the sheet is "floating" the first time it is called (also notice that the background is dimmed nearly to black -- much darker than on the second screenshot below):
![screenshot_2015-12-01-19-04-00](https://cloud.githubusercontent.com/assets/2285034/11509676/ce98157c-985f-11e5-8302-aa4d998d0e10.png)

After I dismiss it and bringing it up again it is displayed correctly:
![screenshot_2015-12-01-19-04-08](https://cloud.githubusercontent.com/assets/2285034/11509690/e0e140b4-985f-11e5-85d6-a1b26c71eb21.png)

I assume this is due to the `WebView` calculating the correct height the first time it is displayed.

Any ideas for a fix or a workaround?

**Comment by markrietveld** [comment]
This seems to be the same thing as https://github.com/Flipboard/bottomsheet/issues/81, which should be fixed by https://github.com/Flipboard/bottomsheet/commit/c3b2e5a254a20889d2f011f3fe9922a75d023c68. I'll try to get a release out today

**Comment by svenwiegand** [comment]
Thanks for the lightning fast response. But the problem still occurs. I was able to track it down to the `layout_height` of my `WebView` set to `wrap_content`. Setting it to `match_parent` generates a clean result but a bottom sheet which too large for its content.

I've build a minimum working example which I could provide you if required (I'm not allowed to upload a ZIP-file here). Here are the most important parts:

The layout:
```xml
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:tools="http://schemas.android.com/tools"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                tools:context=".MainActivity"
                android:background="#ffaa00">

    <com.flipboard.bottomsheet.BottomSheetLayout
        android:id="@+id/bottom_sheet_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <FrameLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">
            <Button
                android:id="@+id/button"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center"
                android:text="Show Bottom Sheet"/>
        </FrameLayout>
    </com.flipboard.bottomsheet.BottomSheetLayout>
</RelativeLayout>
```

The Activity:
```java
package com.example.bootomsheet.app;

import android.app.Activity;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.view.ViewGroup;
import android.webkit.WebView;
import android.widget.FrameLayout;
import com.flipboard.bottomsheet.BottomSheetLayout;

public class MainActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        final BottomSheet bottomSheet = new BottomSheet();
        findViewById(R.id.button).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                ((BottomSheetLayout) findViewById(R.id.bottom_sheet_layout)).showWithSheetView(bottomSheet);
            }
        });
    }

    private class BottomSheet extends WebView {

        public BottomSheet() {
            super(MainActivity.this);
            final FrameLayout.LayoutParams l = new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT);
            setLayoutParams(l);
            loadData(
                    "<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>",
                    null, "utf-8");
        }
    }
}
```

**Comment by markrietveld** [comment]
I plugged this code into the sample and was able to reproduce it too. Thanks!

It seems to be because the `WebView` first reports its size as 420 pixels (on my device), then as 70 pixels, and then as 283 pixels. The animation of the sheet is started after the first time everything is measured, which means the sheet will be animated to 420 pixels, even though it ends up being only 283 pixels. The dim is similarly affected.

We can fix the bad position by clamping the translation to the max translation, and we should. That won't completely fix the issue with views that change size rapidly, like webview. Even with clamping, there is flickering and other jarring behavior. We need to either come up with a way of somehow waiting for a view's size to be stable, or say that these views are not supported with dynamic sizing. Please let me know if you have suggestions. I'll also think about it some more.

In the mean time I think the best thing you can do is call `setSheetHeight` with a value from your dimens.xml before calling `showWithSheet` with a `WebView`

**Comment by svenwiegand** [comment]
I've found a way that works, if it is possible to inflate the view to be shown in the bottom sheet some time before it is actually shown (like in my example). In this case one could add the view somewhere to the layout with visibility set to `INVISIBLE`. The view then has some time to calculate its actual height and when the bottom sheet is shown everything works fine.

Here a slightly adjusted version of the activity's `onCreate()` method from the example above which demonstrates the behavior:
```java
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        final ViewGroup frameLayout = ((ViewGroup) findViewById(R.id.frame_layout));
        final BottomSheet bottomSheet = new BottomSheet();
        frameLayout.addView(bottomSheet);
        bottomSheet.setVisibility(View.INVISIBLE);
        findViewById(R.id.button).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                frameLayout.removeView(bottomSheet);
                bottomSheet.setVisibility(View.VISIBLE);
                ((BottomSheetLayout) findViewById(R.id.bottom_sheet_layout)).showWithSheetView(bottomSheet);
            }
        });
    }
```

If the `BottomSheetLayout` would provide an option to pre-add views that will be used later in `showWithSheetView()`, this would be a big help for these scenarios. It would require the possibility to pre-add *multiple* views, if I am displaying different bottom sheets in my activity. 

But I totally understand if you don't like this solution as it is ... well ... a bit special. A workaround would be a method on the `BottomSheetLayout` to query the final display width (as I understood it is smaller that the screen width on tablets in landscape mode). With this helper method I could reliably setup the mechanism described above on my own...
